/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type MenuCard = {
  _id: string;
  _type: "menuCard";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  sortOrder?: number;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  logo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  heroHeading?: string;
  heroText?: string;
  aboutHeading?: string;
  aboutText?: string;
  phone?: string;
  email?: string;
  address?: string;
  openingHours?: string;
  orderUrl?: string;
  facebookUrl?: string;
  instagramUrl?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | MenuCard
  | SanityImageCrop
  | SanityImageHotspot
  | SiteSettings
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint
  | Slug;

// Source: sanity/lib/queries.ts
// Variable: SITE_SETTINGS_QUERY
// Query: *[_id == "siteSettings"][0]{  logo {    asset->{ _id, url, metadata { lqip, dimensions { width, height } } },    alt,    hotspot,    crop  },  heroImage {    asset->{ _id, url, metadata { lqip, dimensions { width, height } } },    alt,    hotspot,    crop  },  heroHeading,  heroText,  aboutHeading,  aboutText,  phone,  email,  address,  openingHours,  orderUrl,  facebookUrl,  instagramUrl}
export type SITE_SETTINGS_QUERY_RESULT =
  | {
      logo: null;
      heroImage: null;
      heroHeading: null;
      heroText: null;
      aboutHeading: null;
      aboutText: null;
      phone: null;
      email: null;
      address: null;
      openingHours: null;
      orderUrl: null;
      facebookUrl: null;
      instagramUrl: null;
    }
  | {
      logo: {
        asset: {
          _id: string;
          url: string | null;
          metadata: {
            lqip: string | null;
            dimensions: {
              width: number | null;
              height: number | null;
            } | null;
          } | null;
        } | null;
        alt: string | null;
        hotspot: SanityImageHotspot | null;
        crop: SanityImageCrop | null;
      } | null;
      heroImage: {
        asset: {
          _id: string;
          url: string | null;
          metadata: {
            lqip: string | null;
            dimensions: {
              width: number | null;
              height: number | null;
            } | null;
          } | null;
        } | null;
        alt: string | null;
        hotspot: SanityImageHotspot | null;
        crop: SanityImageCrop | null;
      } | null;
      heroHeading: string | null;
      heroText: string | null;
      aboutHeading: string | null;
      aboutText: string | null;
      phone: string | null;
      email: string | null;
      address: string | null;
      openingHours: string | null;
      orderUrl: string | null;
      facebookUrl: string | null;
      instagramUrl: string | null;
    }
  | null;

// Source: sanity/lib/queries.ts
// Variable: MENU_CARDS_QUERY
// Query: *[_type == "menuCard"] | order(sortOrder asc){  _id,  title,  image {    asset->{ _id, url, metadata { lqip, dimensions { width, height } } },    alt,    hotspot,    crop  }}
export type MENU_CARDS_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  image: {
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        lqip: string | null;
        dimensions: {
          width: number | null;
          height: number | null;
        } | null;
      } | null;
    } | null;
    alt: string | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
  } | null;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '*[_id == "siteSettings"][0]{\n  logo {\n    asset->{ _id, url, metadata { lqip, dimensions { width, height } } },\n    alt,\n    hotspot,\n    crop\n  },\n  heroImage {\n    asset->{ _id, url, metadata { lqip, dimensions { width, height } } },\n    alt,\n    hotspot,\n    crop\n  },\n  heroHeading,\n  heroText,\n  aboutHeading,\n  aboutText,\n  phone,\n  email,\n  address,\n  openingHours,\n  orderUrl,\n  facebookUrl,\n  instagramUrl\n}': SITE_SETTINGS_QUERY_RESULT;
    '*[_type == "menuCard"] | order(sortOrder asc){\n  _id,\n  title,\n  image {\n    asset->{ _id, url, metadata { lqip, dimensions { width, height } } },\n    alt,\n    hotspot,\n    crop\n  }\n}': MENU_CARDS_QUERY_RESULT;
  }
}
